name: deploy to ec2
on:
    push:
        branches:
            - main
        paths:
            - result/**
            - vote/**
            - worker/**
            - .github/workflows/deploy-to-ec2.yml
            - docker-compose.yaml
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code 
              uses: actions/checkout@v2
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: login to dockerhub 
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push vote service
              uses: docker/build-push-action@v4
              with:
                context: ./vote
                file: ./vote/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/deployvote:latest
                

            - name: Build and push result service
              uses: docker/build-push-action@v4
              with:
                context: ./result
                file: ./result/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/deployresult:latest

            - name: Build and push worker service
              uses: docker/build-push-action@v4
              with:
                context: ./worker
                file: ./worker/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/deployworker:latest


    deploy-to-ec2:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
        - name: Checkout Code 
          uses: actions/checkout@v2 

        - name: set up ssh
          uses: webfactory/ssh-agent@v0.5.3
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: copy docker-compose file
          run: scp -o StrictHostKeyChecking=no docker-compose.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_IP }}:/home/ubuntu/docker-compose.yaml

        - name: Write .env on the server
          run: |
           ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_IP }} 'cat > /home/ubuntu/.env << "ENVEOF"
            ${{ secrets.EC2_ENV_FILE }}
           ENVEOF
           '
          
        - name: run docker-compose up
          run: ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_IP }} "cd /home/ubuntu && docker compose pull && docker compose up -d"
