name: Build and Push Vote Image to Dhub and ECR

on:
  push:
    branches:
      - main
    paths:
      - './vote/**'
      - '.github/workflows/new-vote-image-to-DH-ECR.yml'

  pull_request:
    branches:
      - main
    paths:
      - './vote/**'
      - '.github/workflows/new-vote-image-to-DH-ECR.yml'

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./vote  
          file: ./vote/Dockerfile  
          push: true
          tags: temple011/vote-repo:latest
