name: Build and Push Vote Image to Dhub and ECR

on:
  push:
    branches:
      - main
    paths:
      - 'evoting-new/vote/**'
      - '.github/workflows/new-vote-image-to-DH-ECR.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'evoting-new/vote/**'
      - '.github/workflows/new-vote-image-to-DH-ECR.yml

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

     
      - name: List contents of vote directory
        run: |
          echo "Repository path: $GITHUB_WORKSPACE"  # Print the absolute path of the repo on the runner
          echo "Listing the directory structure in the workspace:"
          ls -al $GITHUB_WORKSPACE  # List files in the root of the workspace
          ls -al $GITHUB_WORKSPACE/evoting-new  # List the 'evoting-new' folder contents
          ls -al $GITHUB_WORKSPACE/evoting-new/vote  # List the 'vote' folder contents

      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/vote  
          file: ${{ github.workspace }}/vote/Dockerfile  
          push: true
          tags: temple011/vote-repo:latest
