name: Build and Push Vote Image to Dhub and ECR

on:
  push:
    branches:
      - main
    paths:
      - 'vote/**'
      - '.github/workflows/vote-to-dh-ecr.yml'

  pull_request:
      branches:
      - main
      paths:
      - 'vote/**'
      - '.github/workflows/vote-to-dh-ecr.yml'


jobs:
 build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/vote
          file: ${{ github.workspace }}/vote/Dockerfile
          push: true
          tags: temple011/vote-repo:latest



          
      # Step 4: Configure AWS credentials
     # - name: Configure AWS credentials
       ##  with:
       #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       #   aws-region: us-east-1  

      # Step 5: Log in to Amazon ECR
      #- name: Log in to Amazon ECR
       # id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v2

      # Step 6: Set short SHA for tagging
      #- name: Set short SHA
     #   id: vars
      #  run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Step 7: Build and push image
      #- name: Build and push image
        #run:  |
        #  IMAGE_NAME=vote-app
        #  SHA_TAG=${{ steps.vars.outputs.short_sha }}

          # Build the Docker image
         # docker build -t temple011/$IMAGE_NAME:$SHA_TAG ./vote

          # Tag for Docker Hub
       #   docker tag $IMAGE_NAME:$SHA_TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$SHA_TAG

          # Tag for AWS ECR
       #   docker tag $IMAGE_NAME:$SHA_TAG ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:$SHA_TAG

          # Push to Docker Hub
       #   docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$SHA_TAG

          # Push to AWS ECR
        #  docker push ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:$SHA_TAG
