name: Build and Push Vote Image to Dhub and ECR

on:
  push:
    branches:
      - main
    paths:
      - 'evoting-new/vote/**'  # Ensure this is relative to the root directory
      - '.github/workflows/vote-to-dh-nd-ecr.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'evoting-new/vote/**'  # Ensure this is relative to the root directory
      - '.github/workflows/vote-to-dh-nd-ecr.yml'

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: List contents of vote directory
        run: |
         echo "Listing contents of vote directory:"
         ls -al ${{ github.workspace }}/evoting-new/vote  # List files in the 'vote' folder

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/evoting-new/vote  # Use the absolute path to 'vote' directory
          file: ${{ github.workspace }}/evoting-new/vote/Dockerfile 
          push: true
          tags: temple011/vote-repo:latest
