name: Build and Push worker Image to Dhub and ECR

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/worker-to-dh-ecr.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/worker-to-dh-ecr.yml'

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo code
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # check secretes 
      - name: Check secrets exist
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "❌ DOCKERHUB_USERNAME is missing"; else echo "✅ DOCKER_USERNAME is set"; fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "❌ DOCKERHUB_TOKEN is missing"; else echo "✅ DOCKERHUB_TOKEN is set"; fi

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      # Step 5: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 6: Set short SHA for tagging
      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Step 7: Build and push image
      - name: Build and push image
        run:  |
          IMAGE_NAME=image-app
          SHA_TAG=${{ steps.vars.outputs.short_sha }}

          # Build the Docker image
          docker build -t temple011/$IMAGE_NAME:$SHA_TAG ./worker

          # Tag for Docker Hub
          docker tag temple011/$IMAGE_NAME:$SHA_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$SHA_TAG

          # Tag for AWS ECR
          docker tag temple011/$IMAGE_NAME:$SHA_TAG ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:$SHA_TAG

          # Push to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$SHA_TAG

          # Push to AWS ECR
          docker push ${{ steps.login-ecr.outputs.registry }}/$IMAGE_NAME:$SHA_TAG
